#
# Copyright 2018 ABSA Group Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Automatic build

on:
  pull_request:
    branches: [ master ]

jobs:
  build-scala-2_11-spark-2_4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-2_11-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-2_11-
      - name: Switch scala to 2_11
        run: mvn scala-cross-build:change-version -Pscala-2.11
      - name: Build and unit test
        run: mvn clean install
  build-scala-2_12-spark-2_4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-2_12-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-2_12-
      - name: Switch scala to 2_11
        run: mvn scala-cross-build:change-version -Pscala-2.12
      - name: Build and unit test
        run: mvn clean install
