#
# Copyright 2018 ABSA Group Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Automatic build

on:
  pull_request:
    branches: [ master , 'release/**' ]
    types: [assigned, opened, synchronize, reopened, labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: [2.11, 2.12]
        spark: [2.4, 3.1]
        exclude:
          - scala: 2.11
            spark: 3.1
    name: Test with Spark ${{ matrix.spark }} on Scala ${{ matrix.scala }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ matrix.spark }}-${{ matrix.scala }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.spark }}-${{ matrix.scala }}-
      - name: Switch scala to ${{ matrix.scala }}
        run: mvn scala-cross-build:change-version -Pscala-${{ matrix.scala }}
      - name: Build and unit test
        if: ${{ ! contains( github.event.pull_request.labels.*.name, 'NoTestNeeded') }}
        run: mvn clean install --no-transfer-progress -Pspark-${{ matrix.spark }} -Dspan.scale.factor=10
      - name: Build and unit test Atum Examples Scala ${{ matrix.scala }} and Spark ${{ matrix.spark }}
        working-directory: ./examples/atum-examples
        if: ${{ ! contains( github.event.pull_request.labels.*.name, 'NoTestNeeded') }}
        run: |
          mvn scala-cross-build:change-version -Pscala-${{ matrix.scala }}
          mvn clean install --no-transfer-progress -Pspark-${{ matrix.spark }}
